# before_install:
# - openssl aes-256-cbc -K $encrypted_7149eff3fd26_key -iv $encrypted_7149eff3fd26_iv -in deploy_rsa.enc -out deploy_rsa -d

sudo: required
services:
- docker
os:
- linux
env:
  global:
    - DOCKER_IMAGE_NAME="project_green"
    - DOCKER_HUB_ORG="trastanechora"

before_script:
  # - openssl aes-256-cbc -K $encrypted_bfaaa201585a_key -iv $encrypted_bfaaa201585a_iv -in deploy_rsa.enc -out deploy_rsa -d
  - openssl aes-256-cbc -K $encrypted_7149eff3fd26_key -iv $encrypted_7149eff3fd26_iv -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy_rsa
  - ssh-add deploy_rsa
  - sudo docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
script:
  - sudo chmod +x deploy.sh
  - sudo chmod 600 deploy_rsa
after_script:
  # - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
  - sudo docker build -t ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:production-${TRAVIS_BUILD_ID}
  - sudo docker push ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:production-${TRAVIS_BUILD_ID}
  - sudo docker tag ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:production-${TRAVIS_BUILD_ID} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:latest
  - sudo docker push ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:latest
  - ssh-keyscan -H $SSH_IP >> ~/.ssh/known_hosts
  - ssh -v -i deploy_rsa $SSH_USER@$SSH_IP DIR=$ROOT_DIR 'bash -s' < deploy.sh